var DIRECTION_UP = 0;
var DIRECTION_RIGHT = 1;
var DIRECTION_DOWN = 2;
var DIRECTION_LEFT = 3;

module.exports = {
    DIRECTION_UP: DIRECTION_UP,
    DIRECTION_RIGHT: DIRECTION_RIGHT,
    DIRECTION_DOWN: DIRECTION_DOWN,
    DIRECTION_LEFT: DIRECTION_LEFT
}

